name: Deployment

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
        
            - name: Set up Go toolchain
              uses: actions/setup-go@v5

            - name: Build the app
              run: ./scripts/buildprod.sh